version: '3.8'

services:
  password-manager:
    build: .
    container_name: password-manager
    ports:
      - "3020:80"
    restart: unless-stopped
    depends_on:
      - password-manager-backend

  password-manager-backend:
    build: ./server
    container_name: password-manager-backend
    ports:
      - "3021:3021"
    volumes:
      - ./server/data:/app/data
    restart: unless-stopped

